language: scala
scala:
  - 2.12.4
sbt_args: -no-colors
dist: trusty
env:
  - SUBPROJECT=comm
  - SUBPROJECT=rholang
  - SUBPROJECT=roscala
  - SUBPROJECT=rosette
  - SUBPROJECT=storage
before_script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script: ./node/main.sh
script: ./scripts/build-subproject.sh
sudo: required
install: ./scripts/install.sh
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"


