language: scala
jdk: openjdk8
scala:
   - 2.12.4

before_script:
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script: main.sh




# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#     docker push rchain/rchain-comm:latest 
#     fi
